name: Build and Sonar

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-sonar:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # Conceder permissão de execução ao gradlew
      - name: Grant execute permission for Gradlew
        run: chmod +x ./gradlew

      # Configurar Java e Gradle
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: ~/.gradle
          key: gradle-cache-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/settings.gradle') }}
          restore-keys: |
            gradle-cache-

      # Executar o build com sonar
      - name: Build and Sonar Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./gradlew clean build jacocoTestReport sonar

      - name: Exibir relatório de problemas do Gradle
        run: cat build/reports/problems/problems-report.html

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: build/reports/jacoco/test/jacocoTestReport.xml

